import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ArrowRight, Sparkles, Zap, Palette, Code } from "lucide-react";

export default function Home() {
  return (
    <div className="min-h-screen">
      {/* Hero Section */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-20 md:py-32">
        <div className="text-center space-y-8 max-w-4xl mx-auto">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full glass border border-white/10">
            <Sparkles className="w-4 h-4 text-cyber-purple" />
            <span className="text-sm text-muted-foreground">
              AI-Generated Web Designs
            </span>
          </div>

          <h1 className="text-5xl md:text-7xl font-bold tracking-tight">
            <span className="text-gradient-cosmic animate-gradient">
              Aliens Made This
            </span>
          </h1>

          <p className="text-xl md:text-2xl text-muted-foreground max-w-2xl mx-auto">
            A showcase of AI-generated web designs and creations. Exploring the
            boundaries of what&apos;s possible when artificial intelligence meets web
            development.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
            <Link href="/showcase">
              <Button size="lg" variant="gradient" className="group">
                View Showcase
                <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
              </Button>
            </Link>
            <a
              href="https://github.com/kvnloo/aliens-made-this"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Button size="lg" variant="glass">
                <Code className="w-4 h-4" />
                View Source
              </Button>
            </a>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card className="glass border-white/10 hover:border-cyber-purple/50 transition-all duration-300 group">
            <CardContent className="pt-6">
              <div className="space-y-4">
                <div className="w-12 h-12 rounded-lg bg-gradient-purple-teal flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Sparkles className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold">AI-Powered</h3>
                <p className="text-muted-foreground">
                  Every design is generated by advanced AI, pushing the
                  boundaries of automated creativity.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="glass border-white/10 hover:border-electric-teal/50 transition-all duration-300 group">
            <CardContent className="pt-6">
              <div className="space-y-4">
                <div className="w-12 h-12 rounded-lg bg-gradient-teal-orange flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Zap className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold">Live Previews</h3>
                <p className="text-muted-foreground">
                  View and interact with live HTML previews of each creation
                  directly in your browser.
                </p>
              </div>
            </CardContent>
          </Card>

          <Card className="glass border-white/10 hover:border-mystic-pink/50 transition-all duration-300 group">
            <CardContent className="pt-6">
              <div className="space-y-4">
                <div className="w-12 h-12 rounded-lg bg-gradient-orange-pink flex items-center justify-center group-hover:scale-110 transition-transform">
                  <Palette className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold">Modern Design</h3>
                <p className="text-muted-foreground">
                  Featuring glassmorphism, vibrant gradients, and cutting-edge
                  UI/UX patterns.
                </p>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>

      {/* CTA Section */}
      <section className="container mx-auto px-4 sm:px-6 lg:px-8 py-20">
        <Card className="glass border-white/10 bg-gradient-to-br from-cyber-purple/10 via-transparent to-electric-teal/10">
          <CardContent className="pt-6">
            <div className="text-center space-y-6 py-12">
              <h2 className="text-3xl md:text-4xl font-bold">
                Ready to explore?
              </h2>
              <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
                Dive into the showcase and discover what happens when AI takes
                the designer&apos;s seat.
              </p>
              <Link href="/showcase">
                <Button size="lg" variant="gradient" className="group">
                  Browse Creations
                  <ArrowRight className="w-4 h-4 group-hover:translate-x-1 transition-transform" />
                </Button>
              </Link>
            </div>
          </CardContent>
        </Card>
      </section>
    </div>
  );
}
